blank_issues_enabled: false
contact_links: 
  - name: Questions and discussion
    url: https://github.com/Mann-Conomy/tsconfig/discussions/categories/q-a
    about: Please use GitHub Discussions to ask and answer questions.